#!/bin/sh
# check_pkg_payload.sh PKG — fail the build if the assembled .pkg is missing any install root a WORKING
# product needs. A dropped payload is invisible to the OS-floor + signature checks, so it must be asserted
# against the actual pkg contents here.
#
# Motivating regression (2026-07-24): the pkg's updater staging was gated on if(MT2_SPARKLE_FRAMEWORK), a
# cache variable the shared-cmake refactor DELETED. The gate silently went always-false, so 0.5.0 shipped
# with NO updater app and NO scheduled update-check agent -- "Check for Updates" did nothing and there was
# no background check either -- while every other gate (floor, signature, tests) stayed green.
set -u
PKG=${1:?usage: check_pkg_payload.sh PKG}
# 10.9's BSD mktemp needs an explicit template (-t); the GNU-style bare `mktemp -d` fails there.
tmp=$(mktemp -d -t check_pkg_payload 2>/dev/null) || { echo "FAIL: mktemp"; exit 1; }
trap 'rm -rf "$tmp"' EXIT
# --expand-full extracts each component's Payload as a real directory tree (not a cpio archive).
pkgutil --expand-full "$PKG" "$tmp/x" >/dev/null 2>&1 || { echo "FAIL: cannot expand $PKG"; exit 1; }

PAYLOAD=$(find "$tmp/x" -type d -name Payload | head -1)
[ -n "$PAYLOAD" ] || { echo "FAIL: no Payload directory in $PKG"; exit 1; }
SCRIPTS=$(find "$tmp/x" -type d -name Scripts | head -1)

fail=0
need()  { if [ -e "$PAYLOAD/$1" ]; then echo "PASS: $1"; else echo "FAIL: pkg payload missing $1"; fail=1; fi; }
needs() { if [ -n "$SCRIPTS" ] && [ -e "$SCRIPTS/$1" ]; then echo "PASS: script $1"; else echo "FAIL: pkg scripts missing $1"; fail=1; fi; }

# The updater surface -- exactly what the dead gate dropped. App + its scheduled update-check agent.
need  "Library/Application Support/Mavergreen/Trackpad2Updater.app"
need  "Library/LaunchAgents/dev.mavergreen.voodooinputmavericks.updatecheck.plist"
# Core driver surface.
need  "usr/local/lib/voodooinputmavericks/VoodooInputMavericks.kext"
need  "usr/local/sbin/voodooinputmavericks-run"
need  "Library/LaunchDaemons/dev.mavergreen.voodooinputmavericks.plist"
# Prefpane companion (staged in the payload; the postinstall installs it into the SIMBL Plugins dir).
need  "usr/local/share/voodooinputmavericks/VoodooInputMavericksPane.bundle"
# Install scripts (sit beside the component Payload). agent-load.sh is generated by stage_updater.sh and
# sourced by the postinstall to load the update-check agent. (The com.schmonz->dev.modernmavericks migration
# scripts, incl. migrate_autocheck.sh, were retired once that one-time rename population had migrated.)
needs postinstall
needs agent-load.sh
# Both pkg scripts `sh` this helper best-effort, so a pkg missing it would install "fine" and leave the
# pre-rename daemons running beside the new ones. ONE-TIME MIGRATION off the ModernMavericks identity
# (flag day 2026-09-22); DELETABLE with it.
needs flag-day-migration.sh

# --- Install-time messaging (conclusion pane) ----------------------------------------------------
# Motivating regression (2026-09-20): postinstall's two user-facing messages -- "restart to finish"
# and "install SIMBL for the Trackpad pane" -- are `echo`s, and PackageKit routes script stdout to
# /var/log/install.log, which Installer.app never renders. So a 0.5.4 install told the user nothing,
# the prefpane companion sat un-injectable for weeks, and every gate stayed green. The conclusion
# pane is the surface Installer.app DOES show after the scripts run; assert it ships and stays wired.
DIST=$(find "$tmp/x" -maxdepth 1 -type f -name Distribution | head -1)
RSRC=$(find "$tmp/x" -maxdepth 1 -type d -name Resources | head -1)

CONCL=""
if [ -n "$DIST" ]; then
    CONCL=$(sed -n 's/.*<conclusion[^>]*file="\([^"]*\)".*/\1/p' "$DIST" | head -1)
fi
if [ -n "$CONCL" ]; then
    echo "PASS: distribution declares a conclusion pane ($CONCL)"
else
    echo "FAIL: distribution declares no <conclusion> pane -- install-time messages reach only install.log"
    fail=1
fi

if [ -n "$CONCL" ] && [ -f "$RSRC/$CONCL" ]; then
    echo "PASS: conclusion resource $CONCL"
elif [ -n "$CONCL" ]; then
    echo "FAIL: distribution names conclusion $CONCL but Resources/ does not contain it"
    fail=1
fi

# Drift guard: the SIMBL URL the user is sent to lives in BOTH the postinstall (log record) and the
# conclusion (what they actually read). Two copies of a URL is how this rots -- pin them together.
if [ -n "$CONCL" ] && [ -f "$RSRC/$CONCL" ] && [ -n "$SCRIPTS" ] && [ -f "$SCRIPTS/postinstall" ]; then
    u_post=$(grep -oE 'https://[A-Za-z0-9._/-]*SIMBL[A-Za-z0-9._/-]*' "$SCRIPTS/postinstall" | head -1)
    u_conc=$(grep -oE 'https://[A-Za-z0-9._/-]*SIMBL[A-Za-z0-9._/-]*' "$RSRC/$CONCL" | head -1)
    if [ -n "$u_post" ] && [ "$u_post" = "$u_conc" ]; then
        echo "PASS: SIMBL URL matches between postinstall and conclusion ($u_post)"
    else
        echo "FAIL: SIMBL URL drift -- postinstall='$u_post' conclusion='$u_conc'"
        fail=1
    fi
fi

[ "$fail" = 0 ] && echo "ALL PASS: pkg payload complete ($PKG)" || echo "PKG PAYLOAD INCOMPLETE ($PKG)"
exit $fail
